apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idp
  template:
    metadata:
      labels:
        app: idp
    spec:
      containers:
      - name: idp
        image: nginx
